module.exports = {
  id: "eununca",
  nome: "Eu Nunca",
  instrucoes:
    'Como jogar: o bot vai mandar frases começando com "Eu nunca...". ' +
    "Se você JÁ fez aquilo, responda com uma das figurinhas enviadas acima " +
    "(combinem entre vocês o que cada figurinha significa). " +
    "Vocês têm 2 minutos por pergunta antes da próxima!",
  perguntas: [
    "Eu nunca menti pra sair mais cedo do trabalho ou da escola.",
    "Eu nunca dancei sozinho(a) no quarto.",
    "Eu nunca chorei assistindo um filme ou série.",
    "Eu nunca stalkeei o perfil de um ex nas redes sociais.",
    "Eu nunca fingi estar doente pra faltar em algum compromisso.",
    "Eu nunca me arrependi de um post que fiz nas redes sociais.",
    "Eu nunca dormi durante uma reunião ou aula.",
    "Eu nunca esqueci o nome de alguém logo depois de ser apresentado.",
    "Eu nunca comi algo direto da geladeira às 3 da manhã.",
    "Eu nunca falei sozinho(a) pensando que ninguém estava ouvindo.",
    "Eu nunca fingi que não vi uma mensagem pra não responder na hora.",
    "Eu nunca ri em um momento super inapropriado.",
    "Eu nunca inventei uma desculpa pra não ir numa festa.",
    "Eu nunca pesquisei meu próprio nome no Google.",
    "Eu nunca cantei no chuveiro como se estivesse num show.",
    "Eu nunca me tranquei do lado de fora de casa.",
    "Eu nunca respondi uma mensagem de trabalho de madrugada sem precisar.",
    "Eu nunca fingi entender uma piada que não fez sentido pra mim.",
    "Eu nunca usei o mesmo look duas vezes na mesma semana achando que ninguém ia notar.",
    "Eu nunca chorei de tanto rir com alguém do grupo.",
    "Eu nunca terminei uma série inteira numa única madrugada.",
    "Eu nunca mandei mensagem pro grupo errado.",
    "Eu nunca fingi estar em outro lugar pra sair de um compromisso chato.",
    "Eu nunca fui pego(a) falando sozinho(a) no carro.",
    "Eu nunca reli minhas próprias mensagens antes de mandar mais de 3 vezes.",
    "Eu nunca me perdi usando GPS mesmo assim.",
    "Eu nunca comprei algo só porque estava com desconto, sem precisar.",
    "Eu nunca fingi estar sem bateria pra não responder alguém.",
    "Eu nunca dei risada num momento sério sem querer.",
    "Eu nunca decorei a letra de uma música que eu nem gosto tanto assim.",
    "Eu nunca fiquei online só pra ver se uma pessoa específica também estava.",
    "Eu nunca contei a mesma história duas vezes pra mesma pessoa sem perceber.",
    "Eu nunca usei uma desculpa de trânsito quando na verdade dormi demais.",
    "Eu nunca fingi que gostei de um presente que não gostei nada.",
    "Eu nunca cheguei atrasado(a) numa entrevista de emprego.",
    "Eu nunca esqueci uma senha importante e tive que resetar tudo.",
    "Eu nunca fingi tirar uma soneca rápida e dormi horas.",
    "Eu nunca comprei roupa e nunca usei.",
    "Eu nunca chorei assistindo um comercial.",
    "Eu nunca me apaixonei por um personagem fictício.",
    "Eu nunca fiquei falando sozinho(a) ensaiando uma conversa antes de ter ela de verdade.",
    "Eu nunca aceitei um pedido de amizade só pra não ser rude.",
    "Eu nunca fingi estar em uma ligação pra evitar falar com alguém pessoalmente.",
    "Eu nunca deixei de responder uma mensagem por mais de uma semana sem querer.",
    "Eu nunca usei a mesma desculpa pra faltar em dois eventos diferentes.",
    "Eu nunca procurei meu próprio horóscopo mesmo não acreditando nisso.",
    "Eu nunca fingi saber sobre um assunto que não fazia ideia do que era.",
    "Eu nunca escondi um lanche pra não dividir com ninguém.",
    "Eu nunca chorei sozinho(a) no banheiro do trabalho ou da escola.",
    "Eu nunca briguei com alguém por causa de um jogo.",
    "Eu nunca fiquei bravo(a) com um personagem de filme/série como se fosse real.",
    "Eu nunca inventei um nome falso em algum lugar por vergonha.",
    "Eu nunca fingi estar bem quando não estava.",
    "Eu nunca chorei vendo um vídeo de animal fofo.",
    "Eu nunca reclamei da comida e mesmo assim repeti o prato.",
    "Eu nunca fingi que não ouvi alguém me chamando.",
    "Eu nunca perdi um compromisso importante por causa do celular.",
    "Eu nunca ensaiei uma resposta engraçada e não teve a oportunidade de usar.",
    "Eu nunca fiz planos e cancelei tudo de última hora pra ficar em casa.",
    "Eu nunca fingi rir de uma piada que não achei graça nenhuma.",
    "Eu nunca comi um doce escondido pra não dividir.",
    "Eu nunca usei um apelido carinhoso sem querer com a pessoa errada.",
    'Eu nunca demorei mais de um dia pra responder um "oi" de alguém.',
    "Eu nunca joguei um jogo de celular até a bateria acabar.",
    "Eu nunca fingi ter lido um livro/artigo que na verdade não li.",
    "Eu nunca me perdi numa cidade que já conhecia.",
    "Eu nunca comprei ingresso pra um evento e não fui.",
    "Eu nunca simulei uma emergência pra sair de um lugar chato.",
    "Eu nunca troquei o nome de alguém na hora de falar com essa pessoa.",
    "Eu nunca vi a mesma série/filme mais de 5 vezes.",
    "Eu nunca escrevi uma mensagem grande e apaguei tudo antes de mandar.",
    "Eu nunca me arrependi de ter comido demais numa festa.",
    "Eu nunca fingi entender um meme só pra não parecer por fora.",
    'Eu nunca dei desculpa de "problema de internet" quando o problema era outro.',
    "Eu nunca fui pego(a) de surpresa numa videochamada mal arrumado(a).",
    "Eu nunca torci pro time errado só pra provocar alguém.",
    "Eu nunca gastei mais do que devia num aplicativo de delivery.",
    "Eu nunca criei um perfil falso nas redes sociais, nem que fosse só de brincadeira.",
    "Eu nunca fingi estar ocupado(a) pra evitar ajudar em alguma tarefa.",
    "Eu nunca contei um segredo sem querer.",
    "Eu nunca demorei mais de uma hora escolhendo o que assistir e acabei não assistindo nada.",
    "Eu nunca xinguei o trânsito em voz alta sozinho(a) no carro.",
    "Eu nunca esqueci uma data importante de alguém próximo.",
    "Eu nunca fiz greve de silêncio numa discussão boba.",
    "Eu nunca comprei algo caro só pra postar nas redes sociais.",
    "Eu nunca chorei de rir com uma piada ruim.",
    "Eu nunca desisti de uma dieta no mesmo dia que comecei.",
    "Eu nunca fiquei acordado(a) a noite toda por causa do celular.",
    'Eu nunca torci pro personagem "vilão" de um filme/série.',
    "Eu nunca fiz cara de paisagem numa reunião chata.",
    "Eu nunca esqueci onde estacionei o carro.",
    "Eu nunca comi comida de outra pessoa sem perguntar.",
    "Eu nunca fingi que meu celular não tinha sinal pra não atender alguém.",
    "Eu nunca fui pego(a) cantando no espelho.",
    "Eu nunca demorei pra sair da cama mesmo já estando acordado(a) há muito tempo.",
    "Eu nunca inventei uma história só pra não parecer chato(a).",
    "Eu nunca reclamei de estar cansado(a) sem ter feito quase nada no dia.",
    "Eu nunca dei risada alta sozinho(a) lendo alguma mensagem.",
    'Eu nunca deixei de comer algo gostoso só porque estava "de dieta".',
    "Eu nunca briguei com o controle remoto ou com algum aparelho eletrônico.",
    "Eu nunca fiquei confuso(a) sobre qual dia da semana era.",
    "Eu nunca planejei uma resposta perfeita mas travei na hora H.",
    "Eu nunca dei zoom numa foto só pra ver um detalhe bobo.",
    "Eu nunca comprei um curso online e nunca assisti nenhuma aula.",
    "Eu nunca me escondi de alguém no meio de um lugar público.",
    "Eu nunca joguei a real conversa fora e fingi que nada aconteceu.",
  ],
};