module.exports = {
  id: 'eununca18',
  nome: 'Eu Nunca +18',
  instrucoes:
    '🎱 *Jogo só para maiores de 18 anos* — confirme que você tem idade suficiente para este jogo.\n\n' +
    'Como jogar: o bot vai mandar frases como "Eu nunca..." e você responde com suas verdades ou mentiras.\n' +
    'Vamos lá? Mande frase para começar.\n',
  perguntas: [
    'Eu nunca transei no primeiro encontro...',
    'Eu nunca fiz coisa errada e me arrependi...',
    'Eu nunca fui em um lugar sózinho...',
    'Eu nunca transei em lugar público...',
    'Eu nunca tive relações sexuais com duas pessoas ao mesmo tempo...',
    'Eu nunca falei com estranhos na internet e me encontrei pessoalmente...',
    'Eu nunca menti para meus pais...',
    'Eu nunca beijei alguém do mesmo sexo...',
    'Eu nunca usei aplicativo de namoro...',
    'Eu nunca fiquei com pessoa que eu não gostava só por Solidão...',
    'Eu nunca mandei foto íntima para alguém que eu não confiava...',
    'Eu nunca falei mal de alguém pelas costas...',
    'Eu nunca fui em festa de amigo e acabei dormindo lá...',
    'Eu nunca gostei de amigo do meu amigo(a)...',
    'Eu nunca falei "eu te amo" sem sentir...',
    'Eu nunca fiquei com melhor amigo do meu amigo...',
    'Eu nunca falei que ia sair e fiquei em casa...',
    'Eu nunca fiquei com alguém só para esquecer outra pessoa...',
    'Eu nunca falei palavrão na frente dos meus pais...',
    'Eu nunca beijei alguém no primeiro encontro...',
    'Eu nunca fiquei com mais de uma pessoa na mesma noite...',
    'Eu nunca falei mentira tão grande que quase acreditei...',
    'Eu nunca fiquei com amigo do meu ex...',
    'Eu nunca usei roupa de outra pessoa sem pedir...',
    'Eu nunca falei que gostava de alguém só por interesse...',
    'Eu nunca fiquei com alguém e me arrependi no outro dia...',
    'Eu nunca falei que ia ligar e não liguei...',
    'Eu nunca fiquei com alguém que eu não sabia o nome...',
    'Eu nunca falei para minha mãe que ia para um lugar e fui para outro...',
    'Eu nunca fiquei com alguém para impressionar os amigos...',
    'Eu nunca falei que estava doente para não sair de casa...',
    'Eu nunca fiquei com alguém que eu conheci na internet...',
    'Eu nunca falei para meu pai que ia sair e não saí...',
    'Eu nunca fiquei com alguém só para dizer que fiquei...',
    'Eu nunca falei que ia trabalhar e fiquei em casa...',
    'Eu nunca falei que ia estudar e fiquei vendo série...',
    'Eu nunca fiquei com alguém que era comprometido...',
    'Eu nunca falei que estava ocupado para não atender alguém...',
    'Eu nunca fiquei com alguém só para ver como era...',
    'Eu nunca falei que ia comprar algo e não comprei...',
    'Eu nunca falei que ia pagar e não paguei...',
    'Eu nunca fiquei com alguém que eu não gostava só para não ficar sozinho...',
    'Eu nunca falei que ia ajudar e não ajudei...',
    'Eu nunca fiquei com alguém só para ter uma história para contar...',
    'Eu nunca falei que ia chegar cedo e cheguei tarde...',
    'Eu nunca fiquei com alguém para esquecer um ex...',
    'Eu nunca falei que ia devolver e não devolvi...',
    'Eu nunca fiquei com alguém que eu não lembro o nome...',
    'Eu nunca falei que ia mandar mensagem e não mandei...',
    'Eu nunca fiquei com alguém só para dizer que não estou mais disponível...',
    'Eu nunca falei que ia fazer algo e não fiz...',
    'Eu nunca fiquei com alguém que eu não gostava só para experimentar...',
    'Eu nunca falei que ia participar de algo e não participei...',
    'Eu nunca fiquei com alguém só para ver se gostava...',
    'Eu nunca falei que ia dar um presente e não dei...',
    'Eu nunca fiquei com alguém que eu não gostava só por pressão dos amigos...',
'Eu nunca falei que ia sair com amigos e fiquei em casa...',
    'Eu nunca fiquei com alguém só para não ser o único solteiro do grupo...',
    'Eu nunca falei que ia viajar e não viajei...',
    'Eu nunca fiquei com alguém só para ver como era beijar...',
    'Eu nunca falei que ia começar dieta e não comecei...',
    'Eu nunca fiquei com alguém que eu não gostava só para não magoar...',
    'Eu nunca falei que ia começar academia e não comecei...',
    'Eu nunca fiquei com alguém só para ter uma noite de prazer...',
    'Eu nunca falei que ia ligar para alguém e não liguei...',
    'Eu nunca fiquei com alguém que eu não gostava só para não ficar sozinha(o)...',
    'Eu nunca falei que ia enviar um e-mail e não enviei...',
    'Eu nunca fiquei com alguém só para ter uma história para contar aos netos...',
    'Eu nunca falei que ia postar uma foto e não postei...',
    'Eu nunca fiquei com alguém que eu não gostava só para ver o que acontecia...',
    'Eu nunca falei que ia ler um livro e não li...',
    'Eu nunca fiquei com alguém só para dizer que já fiz...',
    'Eu nunca falei que ia visitar alguém e não visitei...',
    'Eu nunca fiquei com alguém só para não ficar carente...',
    'Eu nunca falei que ia participar de um evento e não participei...',
    'Eu nunca fiquei com alguém que eu não gostava só para agradar...',
    'Eu nunca falei que ia fazer um trabalho e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite inesquecível...',
    'Eu nunca falei que ia dar uma festa e não dei...',
    'Eu nunca fiquei com alguém só para ter uma experiência nova...',
    'Eu nunca falei que ia fazer um curso e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que não estou mais virgem...',
    'Eu nunca falei que ia fazer um projeto e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no bar...',
    'Eu nunca falei que ia fazer uma viagem e não fiz...',
    'Eu nunca fiquei com alguém só para ver se era bom...',
    'Eu nunca falei que ia mudar de vida e não mudei...',
    'Eu nunca fiquei com alguém só para dizer que já beijei...',
    'Eu nunca falei que ia fazer uma tatuagem e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de sexo...',
    'Eu nunca falei que ia fazer um piercing e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que não estou mais sozinho...',
    'Eu nunca falei que ia aprender a tocar violão e não aprendi...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no churrasco...',
    'Eu nunca falei que ia fazer um bolo e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já transei...',
    'Eu nunca falei que ia consertar algo e não consertei...',
    'Eu nunca fiquei com alguém só para ter uma noite de loucura...',
    'Eu nunca falei que ia organizar uma festa e não organizei...',
    'Eu nunca fiquei com alguém só para ter uma história para contar na faculdade...',
    'Eu nunca falei que ia fazer um café e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já fiz de tudo...',
    'Eu nunca falei que ia fazer uma massagem e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de paixão...',
    'Eu nunca falei que ia fazer uma caminhada e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no trabalho...',
    'Eu nunca falei que ia fazer um jantar e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já vivi...',
    'Eu nunca falei que ia fazer um piquenique e não fiz...',
'Eu nunca falei que ia fazer um projeto novo e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar aos amigos...',
    'Eu nunca falei que ia fazer um trabalho novo e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que não estou mais virgem...',
    'Eu nunca falei que ia fazer uma festa de aniversário e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de loucura...',
    'Eu nunca falei que ia fazer um jantar romântico e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no churrasco...',
    'Eu nunca falei que ia fazer um piquenique romântico e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já vivi tudo...',
    'Eu nunca falei que ia fazer uma viagem romântica e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de paixão...',
    'Eu nunca falei que ia fazer um bolo de aniversário e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar na faculdade...',
    'Eu nunca falei que ia fazer uma massagem romântica e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já experimentei tudo...',
    'Eu nunca falei que ia fazer uma caminhada na praia e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite inesquecível...',
    'Eu nunca falei que ia fazer um café da manhã na cama e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no trabalho...',
    'Eu nunca falei que ia fazer um jantar especial e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já vivi de tudo...',
    'Eu nunca falei que ia fazer um piquenique especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de prazer...',
    'Eu nunca falei que ia fazer uma festa surpresa e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar aos amigos...',
    'Eu nunca falei que ia fazer um projeto especial e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já experimentei tudo...',
    'Eu nunca falei que ia fazer um trabalho especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de loucura...',
    'Eu nunca falei que ia fazer um jantar especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no churrasco...',
    'Eu nunca falei que ia fazer um piquenique especial e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já vivi tudo...',
    'Eu nunca falei que ia fazer uma viagem especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de paixão...',
    'Eu nunca falei que ia fazer um bolo especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar na faculdade...',
    'Eu nunca falei que ia fazer uma massagem especial e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já experimentei tudo...',
    'Eu nunca falei que ia fazer uma caminhada especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite inesquecível...',
    'Eu nunca falei que ia fazer um café da manhã especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no trabalho...',
    'Eu nunca falei que ia fazer um jantar especial e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já vivi de tudo...',
    'Eu nunca falei que ia fazer um piquenique especial e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite inesquecível...',
    'Eu nunca falei que ia fazer um churrasco e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma história para contar no bar...',
    'Eu nunca falei que ia fazer uma festa do pijama e não fiz...',
    'Eu nunca fiquei com alguém só para dizer que já experimentei...',
    'Eu nunca falei que ia fazer uma viagem de fim de semana e não fiz...',
    'Eu nunca fiquei com alguém só para ter uma noite de prazer...',
'Eu nunca fiquei com alguém só para ter uma noite de prazer...'
  ]
};
