module.exports = {
  id: 'eununca18',
  nome: 'Eu Nunca +18',
  instrucoes:
    '🔞 *Jogo só pra maiores de 18 anos* — confirmem que todo mundo no grupo é adulto antes de começar.\n\n' +
    'Como jogar: o bot vai mandar frases começando com "Eu nunca...". ' +
    'Se você JÁ fez aquilo, responda com uma das figurinhas enviadas acima ' +
    '(combinem entre vocês o que cada figurinha significa). ' +
    'Vocês têm 1 minuto por pergunta antes da próxima!',
  javascript
perguntas: [
    'Eu nunca tive relações sexuais com mais de duas pessoas no mesmo dia ou no mesmo evento.',
    'Eu nunca fiz sexo em um local onde qualquer pessoa passante poderia me ver, como estacionamentos, praias ou parques.',
    'Eu nunca usei substâncias químicas ou drogas especificamente para aumentar a libido ou a performance na cama.',
    'Eu nunca transei com alguém sabendo que essa pessoa era comprometida com um amigo(a) ou conhecido(a) próximo(a).',
    'Eu nunca tive relações sexuais com alguém com uma diferença de idade que causaria choque se as pessoas soubessem.',
    'Eu nunca pratiquei sexo anal ou oral com alguém que eu não considerava atraente, apenas pelo prazer do ato.',
    'Eu nunca tive a experiência de ser dominado(a) ou dominar alguém a ponto de usar algemas, mordaças ou chicotes.',
    'Eu nunca fiz sexo com alguém apenas para me vingar de outra pessoa ou para "dar o troco".',
    'Eu nunca tive relações sexuais em um ambiente profissional durante o horário de trabalho.',
    'Eu nunca senti prazer com algo que a maioria das pessoas consideraria "estranho", "nojento" ou moralmente errado.',
    'Eu nunca gravei um vídeo íntimo com a intenção de enviá-lo para alguém sem que a outra pessoa soubesse.',
    'Eu nunca tive relações sexuais com mais de uma pessoa ao mesmo tempo, como em um ménage ou orgia.',
    'Eu nunca menti sobre minha orientação sexual ou identidade de gênero para conseguir transar com alguém.',
    'Eu nunca usei a sexualidade como moeda de troca para conseguir dinheiro, favores ou poder.',
    'Eu nunca tive um "caso" com alguém que era autoridade sobre mim, como chefe, professor ou mentor.',
    'Eu nunca tive relações sexuais com alguém da família distante ou parente.',
    'Eu nunca fiz sexo oral em alguém em um lugar público sem que as pessoas ao redor percebessem.',
    'Eu nunca usei comida ou bebidas no corpo durante o ato sexual.',
    'Eu nunca tive fantasias sexuais com alguém do mesmo sexo enquanto estava em um relacionamento heterossexual.',
    'Eu nunca fiz sexo com alguém apenas para saber como era a sensação, sem sentir atração real.',
    'Eu nunca tive relações sexuais em um banheiro químico ou de shopping.',
    'Eu nunca usei roupas de couro, látex ou vinil para estimular o prazer.',
    'Eu nunca tive um orgasmo pensando em outra pessoa enquanto estava com meu parceiro(a).',
    'Eu nunca fiz sexo com alguém que eu odiava na vida real.',
    'Eu nunca usei brinquedos sexuais controlados por aplicativo por outra pessoa.',
    'Eu nunca tive relações sexuais em um cemitério ou local considerado sagrado.',
    'Eu nunca fiz sexo oral em alguém enquanto essa pessoa estava em uma chamada de vídeo ou telefone.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de fetiches específicos.',
    'Eu nunca pratiquei spanking (palmadas) ou causei dor proposital para sentir prazer.',
    'Eu nunca tive relações sexuais com alguém que era casado(a) e eu era a "outra pessoa".',
    'Eu nunca fiz sexo em um avião, trem ou ônibus.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de swing.',
    'Eu nunca usei gelo ou cera quente durante o sexo.',
    'Eu nunca tive relações sexuais com alguém que eu considerava meu "inimigo".',
    'Eu nunca fiz sexo oral em alguém em um cinema.',
    'Eu nunca tive relações sexuais com mais de três pessoas em uma única noite.',
    'Eu nunca usei fantasias de personagens ou cosplay para transar.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de WhatsApp erótico.',
    'Eu nunca fiz sexo anal com alguém que eu nunca tinha beijado.',
    'Eu nunca tive relações sexuais em um elevador.',
    'Eu nunca usei algemas reais para prender alguém na cama.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um clube de swing.',
    'Eu nunca fiz sexo oral em alguém enquanto estava em uma festa, escondido(a) em algum canto.',
    'Eu nunca tive relações sexuais com alguém que eu considerava "proibido" por questões religiosas.',
    'Eu nunca usei óleo de massagem ou velas aromáticas para preliminares extremas.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um fórum de BDSM.',
    'Eu nunca fiz sexo oral em alguém em um provador de loja de roupas.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de encontros casuais.',
    'Eu nunca usei mordaças ou vendas nos olhos durante o sexo.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de sexo casual.',
    'Eu nunca fiz sexo oral em alguém em um parque público.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de fetiches.',
    'Eu nunca usei roupas íntimas de materiais exóticos como seda ou renda extrema para seduzir.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de sexo.',
    'Eu nunca fiz sexo oral em alguém em um carro em movimento.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de swing.',
    'Eu nunca usei brinquedos sexuais em público sem que ninguém percebesse.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de sexo casual.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de academia.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de fetiches.',
    'Eu nunca usei fantasias de dominação total durante o sexo.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de sexo.',
    'Eu nunca fiz sexo oral em alguém em um local de culto ou igreja.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de swing.',
    'Eu nunca usei substâncias para retardar a ejaculação ou aumentar a sensibilidade.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de encontros.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de biblioteca.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de fetiches.',
    'Eu nunca usei roupas provocantes para provocar alguém em um ambiente formal.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de sexo.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de hospital ou clínica.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de swing.',
    'Eu nunca usei brinquedos sexuais para estimular outra pessoa em público.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de sexo casual.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de museu.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de fetiches específicos.',
    'Eu nunca usei fantasias de submissão total durante o sexo.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de sexo casual.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de teatro.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de swing.',
    'Eu nunca usei substâncias para aumentar a libido durante o ato.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de encontros casuais.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de aeroporto.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de fetiches.',
    'Eu nunca usei roupas de látex para estimular o prazer.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um grupo de sexo.',
    'Eu nunca fiz sexo oral em alguém em um ambiente de escola ou faculdade.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um site de swing.',
    'Eu nunca usei brinquedos sexuais para estimular a mim mesmo(a) em público.',
    'Eu nunca tive relações sexuais com alguém que eu conheci em um aplicativo de sexo.'
  ]
};
