module.exports = {
  id: "eununca18",
  nome: "Eu Nunca +18",
  instrucoes:
    "🔞 *Jogo só pra maiores de 18 anos* — confirmem que todo mundo no grupo é adulto antes de começar.\n\n" +
    'Como jogar: o bot vai mandar frases começando com "Eu nunca...". ' +
    "Se você JÁ fez aquilo, responda com uma das figurinhas enviadas acima " +
    "(combinem entre vocês o que cada figurinha significa). " +
    "Vocês têm 1 minuto por pergunta antes da próxima!",
perguntas: [
 ```
"Eu nunca fiz sexo com alguém logo na primeira noite sem nem conhecer direito.",
"Eu nunca gozei tanto que tive que lavar os lençóis no dia seguinte.",
"Eu nunca mandei uma foto pelada sem a pessoa pedir.",
"Eu nunca senti tanto tesão por alguém que cheguei a tremer só de olhar.",
"Eu nunca dei um non-stop de sexo sem parar desde o almoço até o café da manhã.",
"Eu nunca deixei alguém gozar na minha boca e engoli sem pensar duas vezes.",
"Eu nunca transei em lugar público onde qualquer um podia nos flagrar.",
"Eu nunca coloquei a mão na cintura de alguém pra puxar pra perto e não soltar mais.",
"Eu nunca roubei uma calcinha ou cueca de alguém depois de transar.",
"Eu nunca fiz sexo anal sem camisinha porque o cara garantiu que era seguro.",
"Eu nunca mordi o lábio de alguém com tanta força que deixou marca.",
"Eu nunca gozei tão forte que joguei a cabeça pra trás e gritei.",
"Eu nunca dei uma chupada tão intensa que a pessoa não conseguiu se mexer.",
"Eu nunca transei com dois amigos(as) na mesma cama enquanto os outros assistiam.",
"Eu nunca usei um vibrador no banho e não apaguei a luz pra ninguém ver.",
"Eu nunca fingi que estava gozando pra apressar o lance e sair logo.",
"Eu nunca fiz um 69 sem avisar e a pessoa não sabia o que fazer.",
"Eu nunca meti dois dedos de uma vez pra ver o quão aberta a pessoa estava pra mais.",
"Eu nunca chupei um pau com tanta intensidade que a pessoa quase me engasgou.",
"Eu nunca transei com a luz apagada porque não suportava ver o corpo do outro.",
"Eu nunca meti tão fundo que a pessoa teve que se segurar pra não gritar.",
"Eu nunca transei com alguém que nem sabia o nome direito.",
"Eu nunca gozei dentro sem camisinha e depois falei opa, esqueci.",
"Eu nunca transei com alguém que mal falava português mas a química era fantástica.",
"Eu nunca levei tapa forte na bunda durante o sexo e pedi mais.",
"Eu nunca meti dois dedos pra abrir e logo em seguida meti um terceiro.",
"Eu nunca fiz sexo no chuveiro com a água escorrendo pelo corpo todo.",
"Eu nunca meti com tanta força que a pessoa pediu pra parar.",
"Eu nunca transei com dois caras na mesma noite e não lembrava nem quem era quem.",
"Eu nunca gozei tanto que tive que buscar papel higiênico pra limpar tudo.",
"Eu nunca meti com tanta força que a cama rangeu a noite toda.",
"Eu nunca fiz sexo com alguém que nem sabia o que era tesão de verdade.",
"Eu nunca dei um rei da noite em cima de uma moto de um jeito que ninguém esquece.",
"Eu nunca meti dois paus ao mesmo tempo e não sabia de qual gostava mais.",
"Eu nunca transei em pé contra a parede porque não tinha cama nem sofá.",
"Eu nunca lambi os mamilos de alguém com tanta vontade até a pessoa gemer.",
"Eu nunca fiz sexo com alguém que usava salto alto até o final do ato.",
"Eu nunca gozei tão rápido que tive que fazer um intervalo pra recuperar.",
"Eu nunca meti com tanta gana que a pessoa teve que me pedir pra parar.",
"Eu nunca fiz sexo com alguém logo após brigar feio pra descontar a raiva.",
"Eu nunca chupei um peitinho tão delicado que a pessoa não conseguia respirar.",
"Eu nunca transei com a pessoa toda molhada e não sabia se era suor ou gozo.",
"Eu nunca meti dois dedos bem devagar pra abrir quem não estava acostumada.",
"Eu nunca gozei tanto que a pessoa pediu pra parar porque estava sensível demais.",
"Eu nunca lambi desde o pescoço até a barriga da pessoa com a língua inteira.",
"Eu nunca transei com alguém que usava salto fino e mancava depois do sexo.",
"Eu nunca meti com calma até a pessoa implorar pra eu acelerar porque doía.",
"Eu nunca fiz sexo com alguém que nem tirava a roupa direito e mesmo assim virou um tesão.",
"Eu nunca gemei tão alto que os vizinhos bateram na parede reclamando.",
"Eu nunca transei com dois caras no mesmo dia e eles ficaram sabendo depois.",
"Eu nunca mordi o ombro de alguém com tanta força que deixou marca roxa.",
"Eu nunca gozei tanto que tive que lavar as mãos e o rosto porque estava tudo grudento.",
"Eu nunca transei com a luz acesa porque achava excitante ver a pessoa nua.",
"Eu nunca meti um pau grosso depois de um fino pra ver como a pessoa se adaptava.",
"Eu nunca lambi desde o pé até o pescoço da pessoa sem pular nenhuma parte.",
"Eu nunca transei com alguém que nem lembrava o nome no dia seguinte.",
"Eu nunca meti dois dedos na vagina e dois no ânus ao mesmo tempo.",
"Eu nunca fiz sexo em qualquer lugar que não fosse cama ou sofá: carro, elevador, praia.",
"Eu nunca gozei tanto que a pessoa precisou colocar gelo pra aliviar a queimação.",
"Eu nunca quis fazer gangbang.",
"Eu nunca fiz suruba.",
"Eu nunca fiz sexo com alguém do mesmo sexo.",
"Eu nunca dei o cu.",
"Eu nunca chorei fazendo sexo.",
"Eu nunca fiz sexo no carro.",
"Eu nunca fui masturbado(a) em lugar público.",
"Eu nunca fiz boquete na rua.",
"Eu nunca transei em uma sacada.",
"Eu nunca transei com professor(a).",
"Eu nunca levei gozada no cuzinho.",
"Eu nunca levei gozada na cara.",
"Eu nunca dei pra um amigo.",
"Eu nunca comi uma amiga.",
"Eu nunca chupei mais de uma pessoa no mesmo dia.",
"Eu nunca quis transar com alguém que acabei de conhecer.",
"Eu nunca transei em uma construção.",
"Eu nunca mandei nudes pra alguém que acabei de conhecer.",
"Eu nunca fiz sexo por dinheiro.",
"Eu nunca fiz sexo no mar.",
"Eu nunca fiz ménage.",
"Eu nunca fui embora logo depois de transar.",
"Eu nunca levei cuspe na boca.",
"Eu nunca fiz garganta profunda.",
"Eu nunca gritei o nome de outra pessoa no meio do sexo.",
"Eu nunca usei comida no corpo de alguém e comi tudo durante o ato.",
"Eu nunca fiz squirt e molhei a cama inteira.",
"Eu nunca amarrei alguém na cama e deixei a pessoa mendigando.",
"Eu nunca chupei os pés de alguém até a pessoa gozar só com isso.",
"Eu nunca gravei um vídeo de sexo sem a pessoa saber no começo.",
"Eu nunca usei um plug anal o dia inteiro sem tirar.",
"Eu nunca fiz deepthroat até as lágrimas descerem.",
"Eu nunca gozei só de ver a pessoa se masturbando na minha frente.",
"Eu nunca deixei alguém me foder com um consolo enquanto eu chupava outro.",
"Eu nunca transava com a janela aberta pra alguém poder ouvir.",
"Eu nunca usei gelo e vela quente no corpo de alguém.",
"Eu nunca fiz sexo no banheiro de um bar lotado.",
"Eu nunca pedi pra ser engasgado durante o boquete.",
"Eu nunca gozei dentro e continuei metendo sem parar.",
"Eu nunca fiz facefuck até a pessoa quase vomitar.",
"Eu nunca usei a própria calcinha como mordaça.",
"Eu nunca transava enquanto outra pessoa dormia no mesmo quarto.",
"Eu nunca chupei o cu de alguém até a pessoa tremer.",
"Eu nunca meti com a pessoa de quatro e puxei o cabelo com força.",
"Eu nunca fiz um creampie e depois chupei tudo de volta.",
"Eu nunca usei dois vibradores ao mesmo tempo em alguém.",
"Eu nunca transava no elevador de um prédio.",
"Eu nunca pedi pra ser cuspido na cara durante o sexo.",
"Eu nunca fiz sexo com a pessoa usando só a roupa de baixo.",
"Eu nunca gozei tantas vezes seguidas que perdi a conta.",
"Eu nunca deixei alguém me foder no banheiro do avião.",
"Eu nunca usei uma coleira e guia durante o sexo.",
"Eu nunca chupei alguém até a pessoa gozar e engoli tudo sem reclamar.",
"Eu nunca meti com a pessoa sentada na pia do banheiro.",
"Eu nunca usei óleo de massagem e escorreguei o corpo inteiro.",
"Eu nunca transava com a porta destrancada esperando ser pego.",
"Eu nunca pedi pra ser engolido até o fundo sem parar pra respirar.",
"Eu nunca gozei só de ser lambido no pescoço e na orelha.",
"Eu nunca fiz sexo em cima da mesa da cozinha.",
"Eu nunca usei um chicote de verdade e deixei marcas.",
"Eu nunca chupei o pau de alguém enquanto ele dirigia.",
"Eu nunca meti com a pessoa de lado e apertei os peitos com força.",
"Eu nunca fiz um golden shower e a pessoa gostou.",
"Eu nunca transava no cinema lotado sem ninguém perceber.",
"Eu nunca pedi pra ser fudido tão fundo que senti no estômago.",
"Eu nunca gozei e continuei sendo chupado até ficar hipersensível.",
"Eu nunca usei um dildo remoto e controlei de longe.",
"Eu nunca fiz sexo no terraço de um prédio alto.",
"Eu nunca chupei os seios de alguém até deixar marca de dente.",
"Eu nunca meti com a pessoa contra o espelho pra ela se ver.",
"Eu nunca fiz um rimjob até a pessoa quase gozar.",
"Eu nunca transava com a pessoa usando salto e meia-calça.",
"Eu nunca pedi pra ser amarrado e abandonado por um tempo.",
"Eu nunca gozei na boca de alguém e mandei engolir na minha frente.",
"Eu nunca usei um anel peniano e fiquei duro por horas.",
"Eu nunca fiz sexo no banheiro de uma festa enquanto a música tocava alto.",
"Eu nunca chupei alguém até as pernas tremerem e a pessoa quase cair.",
"Eu nunca meti com a pessoa de quatro e dei tapa na bunda até ficar vermelha.",
"Eu nunca fiz um double penetration com dedos e pau.",
"Eu nunca transava com a pessoa no colo enquanto assistia filme.",
"Eu nunca pedi pra ser engasgado e cuspido ao mesmo tempo.",
"Eu nunca gozei tanto que a pessoa teve que me limpar com a língua.",
"Eu nunca usei um plug e um vibrador juntos até a pessoa gozar gritando.",
"Eu nunca fiz sexo no carro com o vidro embassado e as luzes acesas.",
"Eu nunca chupei o saco e o pau ao mesmo tempo sem parar.",
"Eu nunca meti com a pessoa de costas e apertei o pescoço de leve.",
"Eu nunca fiz um creampie pie e depois comemos juntos.",
"Eu nunca transava com a pessoa usando só o casaco aberto.",
"Eu nunca pedi pra ser fudido enquanto eu chupava outra pessoa.",
"Eu nunca gozei só de ver a pessoa se tocando com força.",
"Eu nunca usei uma venda e deixei a pessoa fazer o que quisesse.",
"Eu nunca fiz sexo no banheiro de um shopping.",
"Eu nunca chupei alguém até a pessoa gozar e continuei chupando.",
"Eu nunca meti com a pessoa em cima da máquina de lavar ligada.",
"Eu nunca fiz um 69 invertido até os dois gozarem juntos.",
"Eu nunca transava com a pessoa no chão frio porque não aguentava esperar.",
"Eu nunca pedi pra ser engolido até as lágrimas e o ranho descerem.",
"Eu nunca gozei dentro e a pessoa pediu pra eu continuar metendo.",
"Eu nunca usei dois dedos no cu e o pau na boceta ao mesmo tempo.",
"Eu nunca fiz sexo no banheiro de um restaurante caro.",
"Eu nunca chupei os peitos de alguém até a pessoa gozar sem ser tocada embaixo.",
"Eu nunca meti com a pessoa de quatro e puxei os cabelos pra trás.",
"Eu nunca fiz um face sitting até a pessoa quase não aguentar respirar.",
"Eu nunca transava com a pessoa usando só a camisa de botão aberta.",
"Eu nunca pedi pra ser cuspido na boca e engolir na hora.",
"Eu nunca gozei tantas vezes que a pessoa teve que me segurar pra eu não cair.",
"Eu nunca usei um vibrador no clitóris enquanto metia fundo.",
"Eu nunca fiz sexo no elevador de serviço de um hotel.",
"Eu nunca chupei o pau de alguém até a pessoa gozar e eu engolir tudo de uma vez.",
"Eu nunca meti com a pessoa sentada na beira da cama e as pernas no meu ombro.",
"Eu nunca fiz um double oral com outra pessoa no mesmo pau.",
"Eu nunca transava com a pessoa no escuro total e só pelos gemidos.",
"Eu nunca pedi pra ser fudido tão forte que a cama bateu na parede a noite toda.",
"Eu nunca gozei e a pessoa lambia tudo enquanto eu ainda tremia.",
"Eu nunca usei um plug anal e um collor no pescoço ao mesmo tempo.",
"Eu nunca fiz sexo no banheiro de uma balada com a porta só encostada.",
"Eu nunca chupei alguém até a pessoa implorar pra eu parar de tanta sensibilidade.",
"Eu nunca meti com a pessoa de lado e gozei tão fundo que ela sentiu escorrendo.",
"Eu nunca fiz um 69 até a gente quase não conseguir respirar.",
"Eu nunca transava com a pessoa em cima do sofá da sala com a TV ligada.",
"Eu nunca pedi pra ser engasgado e ter o cabelo puxado ao mesmo tempo.",
"Eu nunca gozei tanto que a pessoa teve que me dar água depois.",
"Eu nunca usei um dildo na boceta e o pau no cu ao mesmo tempo.",
"Eu nunca fiz sexo no carro embaixo de um viaduto.",
"Eu nunca chupei os lábios e a língua de alguém enquanto metia fundo.",
"Eu nunca meti com a pessoa de quatro e dei tapa forte até ela gozar.",
"Eu nunca fiz um creampie e depois fiz a pessoa se olhar no espelho.",
"Eu nunca transava com a pessoa usando só a gravata e os sapatos.",
"Eu nunca pedi pra ser fudido enquanto eu me masturbava.",
"Eu nunca gozei só de ter os mamilos chupados e mordidos.",
"Eu nunca usei uma mordaça de bola e uma venda juntas.",
"Eu nunca fiz sexo no banheiro de um ônibus interestadual.",
"Eu nunca chupei o pau e os ovos de alguém até a pessoa gozar gritando.",
"Eu nunca meti com a pessoa contra a parede e segurei as mãos acima da cabeça.",
"Eu nunca fiz um facefuck até a pessoa babar e o rímel escorrer.",
"Eu nunca transava com a pessoa no chão do quarto com os travesseiros jogados.",
"Eu nunca pedi pra ser engolido até o fundo e ficar parado lá.",
"Eu nunca gozei dentro e a pessoa pediu pra eu gozar de novo em cima.",
"Eu nunca usei um vibrador no cu e o pau na boceta juntos.",
"Eu nunca fiz sexo no terraço de um motel.",
"Eu nunca chupei alguém até a pessoa tremer e quase desmaiar de prazer.",
"Eu nunca meti com a pessoa de costas e apertei os seios com força.",
"Eu nunca fiz um 69 até a gente gozar ao mesmo tempo e se sujar todo.",
"Eu nunca transava com a pessoa em cima da mesa de jantar.",
"Eu nunca pedi pra ser cuspido e engasgado até quase não aguentar.",
"Eu nunca gozei tanto que a pessoa teve que me limpar com uma toalha.",
"Eu nunca usei um plug e um vibrador de controle remoto ao mesmo tempo.",
"Eu nunca fiz sexo no banheiro de uma universidade.",
"Eu nunca chupei o pau de alguém enquanto ele me dedava forte.",
"Eu nunca meti com a pessoa de quatro e puxei a cabeça pra trás.",
"Eu nunca fiz um double penetration com pau e dildo.",
"Eu nunca transava com a pessoa no colo da poltrona.",
"Eu nunca pedi pra ser fudido enquanto eu chupava os próprios peitos.",
"Eu nunca gozei só de ser dedado e chupado ao mesmo tempo.",
"Eu nunca usei uma coleira e um chicote leves.",
"Eu nunca fiz sexo no carro no estacionamento de um shopping.",
"Eu nunca chupei alguém até a pessoa gozar e eu continuar lambendo.",
"Eu nunca meti com a pessoa sentada na pia e as pernas abertas.",
"Eu nunca fiz um creampie e depois fiz a pessoa segurar tudo dentro.",
"Eu nunca transava com a pessoa usando só a jaqueta de couro.",
"Eu nunca pedi pra ser engasgado até as lágrimas e o ranho.",
"Eu nunca gozei tantas vezes que a pessoa ficou preocupada.",
"Eu nunca usei dois vibradores e o pau ao mesmo tempo.",
"Eu nunca fiz sexo no banheiro de um cinema.",
"Eu nunca chupei os peitos e a boceta de alguém até ela gozar gritando.",
"Eu nunca meti com a pessoa de lado e gozei tão fundo que escorreu.",
"Eu nunca fiz um 69 até a gente quase não conseguir se mexer.",
"Eu nunca transava com a pessoa no chão da cozinha.",
"Eu nunca pedi pra ser fudido tão forte que a cama quebrou.",
"Eu nunca gozei e a pessoa chupou tudo enquanto eu ainda gozava.",
"Eu nunca usei um plug anal o dia inteiro e só tirei na hora do sexo.",
"Eu nunca fiz sexo no elevador de um prédio residencial.",
"Eu nunca chupei o pau de alguém até ele gozar e eu engolir sem engasgar.",
"Eu nunca meti com a pessoa de quatro e dei tapa até a bunda ficar roxa.",
"Eu nunca fiz um face sitting até a pessoa pedir ar.",
"Eu nunca transava com a pessoa em cima da escrivaninha.",
"Eu nunca pedi pra ser cuspido na cara e na boca.",
"Eu nunca gozei tanto que a pessoa teve que me dar um tempo.",
"Eu nunca usei um dildo e o pau no mesmo buraco.",
"Eu nunca fiz sexo no carro em uma estrada deserta.",
"Eu nunca chupei alguém até a pessoa gozar e eu continuar chupando sensível.",
"Eu nunca meti com a pessoa contra o espelho e fiz ela se olhar.",
"Eu nunca fiz um 69 invertido até os dois gozarem.",
"Eu nunca transava com a pessoa no sofá da sala com a porta aberta.",
"Eu nunca pedi pra ser engasgado e ter o cabelo puxado forte.",
"Eu nunca gozei dentro e continuei metendo até gozar de novo.",
"Eu nunca usei um vibrador no clitóris e no cu ao mesmo tempo.",
"Eu nunca fiz sexo no banheiro de um hospital.",
"Eu nunca chupei o pau e o cu de alguém no mesmo dia.",
"Eu nunca meti com a pessoa de costas e apertei o pescoço.",
"Eu nunca fiz um creampie pie e depois beijei a pessoa.",
"Eu nunca transava com a pessoa usando só as meias e o salto.",
"Eu nunca pedi pra ser fudido enquanto eu me tocava.",
"Eu nunca gozei só de ter a língua no meu ouvido e no pescoço.",
"Eu nunca usei uma venda e uma mordaça juntas.",
"Eu nunca fiz sexo no banheiro de um aeroporto.",
"Eu nunca chupei alguém até a pessoa tremer e gozar sem eu tocar embaixo.",
"Eu nunca meti com a pessoa de quatro e puxei os braços pra trás.",
"Eu nunca fiz um double oral até a pessoa gozar na minha e na dela.",
"Eu nunca transava com a pessoa no chão do banheiro molhado.",
"Eu nunca pedi pra ser engolido até o fundo e ficar parado.",
"Eu nunca gozei e a pessoa lambia enquanto eu ainda gozava.",
"Eu nunca usei um plug e um anel peniano juntos.",
"Eu nunca fiz sexo no terraço de um prédio comercial.",
"Eu nunca chupei os seios de alguém até deixar marca e a pessoa gozar.",
"Eu nunca meti com a pessoa sentada na beira da mesa.",
"Eu nunca fiz um 69 até a gente sujar a cama inteira.",
"Eu nunca transava com a pessoa em cima da máquina de secar roupa.",
"Eu nunca pedi pra ser cuspido e engasgado até quase vomitar.",
"Eu nunca gozei e a pessoa continuou metendo até eu pedir arrego.",
"Eu nunca usei dois dildos e o pau ao mesmo tempo.",
"Eu nunca fiz sexo no carro no estacionamento de um hotel.",
"Eu nunca chupei o pau de alguém enquanto ele me fodia com os dedos.",
"Eu nunca meti com a pessoa de lado e gozei tão forte que ela sentiu.",
"Eu nunca fiz um facefuck até a pessoa babar no meu pau.",
"Eu nunca transava com a pessoa no colo da cadeira de escritório.",
"Eu nunca pedi pra ser fudido tão fundo que senti no fundo da garganta.",
"Eu nunca gozei só de ser lambido do pescoço até a virilha.",
"Eu nunca usei uma coleira e um plug juntos.",
"Eu nunca fiz sexo no banheiro de uma igreja abandonada.",
"Eu nunca chupei alguém até a pessoa gozar e eu engolir tudo quente.",
"Eu nunca meti com a pessoa contra a parede e segurei as pernas.",
"Eu nunca fiz um creampie e depois fiz a pessoa se limpar com o dedo.",
"Eu nunca transava com a pessoa usando só a camisa social aberta.",
"Eu nunca pedi pra ser engasgado até as lágrimas e o rímel escorrer.",
"Eu nunca gozei tantas vezes que perdi a força nas pernas.",
"Eu nunca usei um vibrador de controle remoto em público.",
"Eu nunca fiz sexo no elevador panorâmico.",
"Eu nunca chupei o pau e os peitos de alguém ao mesmo tempo.",
"Eu nunca meti com a pessoa de quatro e dei tapa forte na bunda.",
"Eu nunca fiz um 69 até a gente gozar e continuar lambendo.",
"Eu nunca transava com a pessoa no chão da sala com a luz apagada.",
"Eu nunca pedi pra ser fudido enquanto eu chupava o próprio dedo.",
"Eu nunca gozei e a pessoa chupou tudo enquanto eu ainda pulsava.",
"Eu nunca usei um dildo no cu e o pau na boceta.",
"Eu nunca fiz sexo no carro em um posto de gasolina deserto.",
"Eu nunca chupei alguém até a pessoa implorar pra eu parar e continuar.",
"Eu nunca meti com a pessoa de costas e apertei os seios forte.",
"Eu nunca fiz um double penetration com dedos e língua.",
"Eu nunca transava com a pessoa em cima do balcão da cozinha.",
"Eu nunca pedi pra ser cuspido na boca e beijar depois.",
"Eu nunca gozei tanto que a pessoa teve que me carregar até a cama.",
"Eu nunca usei um plug anal e um vibrador no clitóris juntos.",
"Eu nunca fiz sexo no banheiro de um shopping center.",
"Eu nunca chupei o pau de alguém até ele gozar na minha garganta.",
"Eu nunca meti com a pessoa sentada na beira da banheira.",
"Eu nunca fiz um face sitting até a pessoa quase desmaiar.",
"Eu nunca transava com a pessoa no sofá com a janela aberta.",
"Eu nunca pedi pra ser engasgado e ter a cara segurada.",
"Eu nunca gozei dentro e a pessoa pediu pra eu gozar na boca depois.",
"Eu nunca usei dois vibradores e continuei metendo.",
"Eu nunca fiz sexo no terraço de um hotel barato.",
"Eu nunca chupei os peitos e a boceta até a pessoa gozar duas vezes.",
"Eu nunca meti com a pessoa de quatro e puxei o cabelo com as duas mãos.",
"Eu nunca fiz um 69 até a gente não aguentar mais e gozar.",
"Eu nunca transava com a pessoa no chão do quarto com os lençóis no chão.",
"Eu nunca pedi pra ser fudido tão forte que a parede tremeu.",
"Eu nunca gozei e continuei sendo chupado até ficar mole e duro de novo.",
"Eu nunca usei um anel peniano e um plug juntos.",
"Eu nunca fiz sexo no banheiro de um bar com a fila do lado de fora.",
"Eu nunca chupei alguém até a pessoa gozar e eu lamber os restos.",
"Eu nunca meti com a pessoa contra o espelho do banheiro.",
"Eu nunca fiz um creampie e depois beijei a pessoa com gosto.",
"Eu nunca transava com a pessoa usando só a gravata no pescoço.",
"Eu nunca pedi pra ser engasgado até quase não aguentar e continuar.",
"Eu nunca gozei tanto que a pessoa teve que me dar um copo de água.",
"Eu nunca usei um dildo remoto e controlei enquanto a pessoa trabalhava.",
"Eu nunca fiz sexo no carro no estacionamento de um hospital.",
"Eu nunca chupei o pau de alguém enquanto ele me dedava o cu.",
"Eu nunca meti com a pessoa de lado e gozei tão fundo que escorreu pelas pernas.",
"Eu nunca fiz um facefuck até a pessoa babar e o rímel escorrer todo.",
"Eu nunca transava com a pessoa no colo da cadeira de balanço.",
"Eu nunca pedi pra ser fudido enquanto eu me masturbava forte.",
"Eu nunca gozei só de ter a língua no meu cu e nos ovos.",
"Eu nunca usei uma venda, mordaça e coleira juntas.",
  ],
};
