module.exports = {
  id: 'verdadeoudesafio18',
  nome: 'Verdade ou Desafio +18',
  instrucoes:
    'Como jogar: o bot alterna entre 🗣️ VERDADE (uma pergunta +18 para responder de verdade) ' +
    'e 🎯 DESAFIO (uma ação +18 para fazer e mostrar no grupo). ' +
    'Depois de responder a verdade ou cumprir o desafio, manda uma das figurinhas enviadas acima pra avisar que terminou. ' +
    'Vocês têm 1 minuto por rodada antes da próxima!',
  perguntas: [
    '🗣️ VERDADE: Qual foi a situação mais constrangedora ou bizarra que você já passou durante o sexo?',
    '🎯 DESAFIO: Mande uma foto da sua lingerie ou cueca atual (ou de algo que você usaria para seduzir).',
    '🗣️ VERDADE: Qual foi o lugar mais público e arriscado onde você já transou ou se masturbou?',
    '🎯 DESAFIO: Grave um áudio descrevendo detalhadamente a sua fantasia sexual mais secreta.',
    '🗣️ VERDADE: Você já fingiu um orgasmo para acabar logo com a transa? Com quem e por quê?',
    '🎯 DESAFIO: Mande um print do seu histórico de buscas do navegador com termos eróticos ou fetiches.',
    '🗣️ VERDADE: Qual foi a pessoa mais "proibida" ou inesperada com quem você já teve relações?',
    '🎯 DESAFIO: Escreva uma mensagem extremamente picante para a pessoa que você mais deseja no grupo.',
    '🗣️ VERDADE: Qual é a prática sexual que você sempre quis experimentar, mas tem vergonha de pedir?',
    '🎯 DESAFIO: Grave um áudio sussurrando no ouvido de quem você quer, descrevendo o que faria com ela agora.',
    '🗣️ VERDADE: Você já teve relações sexuais com mais de uma pessoa ao mesmo tempo? Como foi?',
    '🎯 DESAFIO: Mande uma foto de uma parte do seu corpo que você considera a mais erógena/sensual.',
    '🗣️ VERDADE: Qual foi a pior experiência sexual da sua vida e o que tornou tudo tão ruim?',
    '🎯 DESAFIO: Mande uma foto do seu corpo (sem mostrar o rosto) em uma pose provocante.',
    '🗣️ VERDADE: Qual foi a coisa mais ousada ou "suja" que você já fez na cama?',
    '🎯 DESAFIO: Grave um áudio descrevendo qual posição sexual é a sua favorita e por que ela te excita.',
    '🗣️ VERDADE: Você já mandou nudes para a pessoa errada ou teve algum vazamento de conteúdo íntimo?',
    '🎯 DESAFIO: Mande um sticker erótico e marque a pessoa que você gostaria de fazer aquilo agora.',
    '🗣️ VERDADE: Qual foi a experiência sexual mais surpreendente ou intensa que você já teve?',
    '🎯 DESAFIO: Mande o link de um vídeo pornô ou cena que represente exatamente o seu gosto sexual.',
    '🗣️ VERDADE: Qual a sua opinião real sobre sexo anal? Já praticou ou gostaria de praticar?',
    '🎯 DESAFIO: Mande um áudio fazendo um gemido sensual de 5 segundos.',
    '🗣️ VERDADE: Você já teve algum fetiche por pés ou outras partes do corpo consideradas estranhas?',
    '🎯 DESAFIO: Tire uma foto da sua mão tocando a região da sua coxa o mais próximo possível da genitália.',
    '🗣️ VERDADE: Qual foi a maior quantidade de pessoas que você já teve em uma única cama?',
    '🎯 DESAFIO: Descreva em 3 palavras o que você faria se estivesse sozinho(a) com a pessoa mais sexy do grupo.',
    '🗣️ VERDADE: Você já transou com alguém que você odeia ou não suporta?',
    '🎯 DESAFIO: Mande um áudio dizendo "eu sou um(a) safado(a)" com a voz mais provocante que conseguir.',
    '🗣️ VERDADE: Qual a coisa mais "suja" que você já falou durante o sexo?',
    '🎯 DESAFIO: Mande uma foto de um objeto da sua casa que você usaria como brinquedo sexual.',
    '🗣️ VERDADE: Você já se masturbou pensando em alguém que está neste grupo?',
    '🎯 DESAFIO: Mande um print de uma conversa picante que você já teve (censurando nomes).',
    '🗣️ VERDADE: Qual foi o sonho erótico mais louco que você já teve com alguém conhecido?',
    '🎯 DESAFIO: Grave um áudio descrevendo como seria o seu encontro perfeito de "uma noite só".',
    '🗣️ VERDADE: Você já teve relações sexuais em um carro? Onde e como foi?',
    '🎯 DESAFIO: Mande uma foto de você mordendo o próprio lábio de forma sensual.',
    '🗣️ VERDADE: Qual a sua posição favorita para chegar ao orgasmo rapidamente?',
    '🎯 DESAFIO: Escolha alguém do grupo e diga qual parte do corpo dela você gostaria de lamber agora.',
    '🗣️ VERDADE: Você já usou algum brinquedo sexual enquanto estava com outra pessoa?',
    '🎯 DESAFIO: Mande um áudio imitando o som de alguém tendo um orgasmo.',
    '🗣️ VERDADE: Qual foi a maior loucura que você já fez para conseguir transar com alguém?',
    '🎯 DESAFIO: Mande uma foto do seu pescoço ou clavícula de forma provocante.',
    '🗣️ VERDADE: Você já teve algum "caso" com alguém do trabalho ou faculdade?',
    '🎯 DESAFIO: Escreva um pequeno conto erótico de 3 linhas envolvendo você e alguém do grupo.',
    '🗣️ VERDADE: Qual a sua fantasia mais obscena que você nunca contou para ninguém?',
    '🎯 DESAFIO: Mande um áudio descrevendo onde você gostaria que te tocassem agora.',
    '🗣️ VERDADE: Você já fez sexo oral em alguém em um lugar onde corria risco de ser pego?',
    '🎯 DESAFIO: Mande uma foto da sua língua de forma sensual.',
    '🗣️ VERDADE: Qual a coisa mais ousada que você já fez usando roupas íntimas em público?',
    '🎯 DESAFIO: Mande um áudio dizendo qual a sua preferência: dominar ou ser dominado(a).',
    '🗣️ VERDADE: Você já teve relações sexuais com alguém significativamente mais velho ou mais novo?',
    '🎯 DESAFIO: Mande uma foto de você fingindo que está tirando a roupa.',
    '🗣️ VERDADE: Qual foi a experiência sexual mais curta e mais longa que você já teve?',
    '🎯 DESAFIO: Mande um áudio descrevendo a sensação de um beijo no pescoço.',
    '🗣️ VERDADE: Você já usou substâncias para aumentar a libido durante o sexo?',
    '🎯 DESAFIO: Mande um print de um perfil de alguém que você acha extremamente sexy.',
    '🗣️ VERDADE: Você já teve relações sexuais com alguém do mesmo sexo?',
    '🎯 DESAFIO: Grave um áudio descrevendo como você gosta de ser tocado(a) nas preliminares.',
    '🗣️ VERDADE: Qual a sua opinião sobre sexo em grupo ou troca de casais?',
    '🎯 DESAFIO: Mande uma foto de você fazendo uma expressão de "quero mais".',
    '🗣️ VERDADE: Você já se masturbou em um lugar público?',
    '🎯 DESAFIO: Mande um áudio sussurrando "eu quero você" para a pessoa mais atraente do grupo.',
    '🗣️ VERDADE: Qual foi a coisa mais estranha que já aconteceu durante o sexo?',
    '🎯 DESAFIO: Mande uma foto da sua roupa atual, mas com um detalhe "revelador".',
    '🗣️ VERDADE: Você já teve relações sexuais com alguém que era comprometido(a)?',
    '🎯 DESAFIO: Descreva a sensação de ter um orgasmo em um áudio de 10 segundos.',
    '🗣️ VERDADE: Qual a sua parte favorita do corpo de um parceiro(a) na hora H?',
    '🎯 DESAFIO: Mande uma foto de você mordendo um dedo de forma sensual.',
    '🗣️ VERDADE: Você já teve relações sexuais em um banheiro público?',
    '🎯 DESAFIO: Mande um áudio dizendo qual a sua "palavra-chave" para sexo.',
    '🗣️ VERDADE: Qual a fantasia sexual que você considera "estranha" demais para os outros?',
    '🎯 DESAFIO: Mande uma foto de você fazendo pose de "safado(a)".',
    '🗣️ VERDADE: Você já fez sexo oral em alguém enquanto essa pessoa dormia ou estava inconsciente?',
    '🎯 DESAFIO: Mande um áudio descrevendo a textura da pele de alguém que você deseja.',
    '🗣️ VERDADE: Qual foi a vez que você mais demorou para chegar ao orgasmo?',
    '🎯 DESAFIO: Mande uma foto de você com a camisa levemente aberta.',
    '🗣️ VERDADE: Você já teve relações sexuais com alguém que conheceu em um app de fetiches?',
    '🎯 DESAFIO: Mande um áudio descrevendo a posição sexual mais difícil que você já tentou.',
    '🗣️ VERDADE: Qual a coisa mais ousada que você já fez em um encontro casual?',
    '🎯 DESAFIO: Mande uma foto de você fazendo um "beijinho" para a câmera.',
    '🗣️ VERDADE: Você já teve relações sexuais com alguém que era autoridade sobre você?',
    '🎯 DESAFIO: Mande um áudio descrevendo o que você sente quando é tocado(a) nas costas.',
    '🗣️ VERDADE: Qual a sua maior insegurança na hora do sexo?',
    '🎯 DESAFIO: Mande uma foto de você fingindo que está sentindo prazer.'
  ]
};
